export const MAJORS = [
  "Computer Science",
  "Software Engineering",
  "Data Science",
  "Cybersecurity",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Nursing",
  "Pre-Med / Biology",
  "Public Health",
  "Neuroscience",
  "Psychology",
  "Business Administration",
  "Finance",
  "Accounting",
  "Marketing",
  "Economics",
  "International Relations",
  "Political Science",
  "Law / Pre-Law",
  "Communications",
  "Journalism",
  "English / Creative Writing",
  "History",
  "Philosophy",
  "Sociology",
  "Anthropology",
  "Education",
  "Elementary Education",
  "Secondary Education",
  "Environmental Science",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Statistics",
  "Architecture",
  "Graphic Design",
  "Industrial Design",
  "Film & Media",
  "Music",
  "Theater / Performing Arts",
  "Fine Arts",
  "Kinesiology / Sports Science",
  "Culinary Arts",
  "Hospitality Management",
  "Supply Chain Management",
  "Entrepreneurship",
  "Undecided / Exploring",
] as const;

export const ACTIVITY_CATEGORIES = [
  "Club",
  "Sport",
  "Robotics",
  "Volunteer",
  "Internship",
  "Job",
  "Competition",
  "Leadership",
  "Research",
  "Personal Project",
  "Arts",
  "Music",
  "Other",
] as const;

export type ActivityCategory = (typeof ACTIVITY_CATEGORIES)[number];

export function formatMajors(majors: string[]): string {
  if (majors.length === 0) return "";
  if (majors.length === 1) return majors[0];
  return `${majors.slice(0, -1).join(", ")} & ${majors[majors.length - 1]}`;
}
